// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQryB-EES55jLcyiERcO8aMm9tU6N9Tro',
    appId: '1:956062479747:web:c16c0af6fbe0fc2243f2b6',
    messagingSenderId: '956062479747',
    projectId: 'healthcare-ca64f',
    authDomain: 'healthcare-ca64f.firebaseapp.com',
    storageBucket: 'healthcare-ca64f.appspot.com',
    measurementId: 'G-30L5B22KKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB59BmdXt9NHnr6uPU8-l-4qoQFSLmSPjA',
    appId: '1:956062479747:android:3cde3399fa540b3043f2b6',
    messagingSenderId: '956062479747',
    projectId: 'healthcare-ca64f',
    storageBucket: 'healthcare-ca64f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIEiFa-SuD8ZBC4hY0ITy-ntqBOprRiTo',
    appId: '1:956062479747:ios:f7794692e4bdbc9443f2b6',
    messagingSenderId: '956062479747',
    projectId: 'healthcare-ca64f',
    storageBucket: 'healthcare-ca64f.appspot.com',
    iosBundleId: 'com.example.semesterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIEiFa-SuD8ZBC4hY0ITy-ntqBOprRiTo',
    appId: '1:956062479747:ios:f7794692e4bdbc9443f2b6',
    messagingSenderId: '956062479747',
    projectId: 'healthcare-ca64f',
    storageBucket: 'healthcare-ca64f.appspot.com',
    iosBundleId: 'com.example.semesterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQryB-EES55jLcyiERcO8aMm9tU6N9Tro',
    appId: '1:956062479747:web:b29cbbd6cffdcf5643f2b6',
    messagingSenderId: '956062479747',
    projectId: 'healthcare-ca64f',
    authDomain: 'healthcare-ca64f.firebaseapp.com',
    storageBucket: 'healthcare-ca64f.appspot.com',
    measurementId: 'G-74V4LK6JGM',
  );
}
